# This file was generated by GoReleaser. DO NOT EDIT.
cask "adassay" do
  version "0.2.1"

  on_macos do
    on_arm do
      sha256 "872110e0f24655e21e5a9b2ff643cbc1ad07e78bcc9d409893c37ced8eb24cf6"
      url "https://github.com/belaytzev/adassay/releases/download/v#{version}/adassay_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "140768b6b3be14e91dfa85e2bbe454a322fccc75191e53014a5c042a1827ed43"
      url "https://github.com/belaytzev/adassay/releases/download/v#{version}/adassay_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "c37b6ca67b8007e725b84b19471208b0b0e7d0d0269a359423d6b6b141155335"
      url "https://github.com/belaytzev/adassay/releases/download/v#{version}/adassay_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b92892c2ca3d0aeb4acaf79f044128045f75345640c4b3f48776976df09b84ab"
      url "https://github.com/belaytzev/adassay/releases/download/v#{version}/adassay_#{version}_linux_amd64.tar.gz"
    end
  end

  name "adassay"
  desc "An ad blocker for AI agents"
  homepage "https://adassay.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "adassay"
  binary "adassay-mcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/adassay"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/adassay-mcp"]
    end
  end

  # No zap stanza required
end
