# This file was generated by GoReleaser. DO NOT EDIT.
cask "adassay" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "75a054d963112809a3590ba98fc41348760af666a0f4c58b208578d997d50479"
      url "https://github.com/belaytzev/adassay/releases/download/v#{version}/adassay_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "162d715a03b5cabec9b2553b03d88013aeebe7577b0fbdd3cac092e246699962"
      url "https://github.com/belaytzev/adassay/releases/download/v#{version}/adassay_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "0ed21de54e8b3154628bdb45638dbc3748c38cb1fa7f893fd387daf50c409dd5"
      url "https://github.com/belaytzev/adassay/releases/download/v#{version}/adassay_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "6426d8f6dfd013897c41e56260f1620aff5e0e20a31069c2af031253acd09a5f"
      url "https://github.com/belaytzev/adassay/releases/download/v#{version}/adassay_#{version}_linux_amd64.tar.gz"
    end
  end

  name "adassay"
  desc "An ad blocker for AI agents"
  homepage "https://adassay.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "adassay"
  binary "adassay-mcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/adassay"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/adassay-mcp"]
    end
  end

  # No zap stanza required
end
