# This file was generated by GoReleaser. DO NOT EDIT.
cask "adassay" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "37a3aa36049aae447a04780072559742c468dd07ae1357d32a551a91b803cc4d"
      url "https://github.com/belaytzev/adassay/releases/download/v#{version}/adassay_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "74f7ca1b40ca387cff51df8ae78affc7d0c615c355680ab26ed11fcbe54b6964"
      url "https://github.com/belaytzev/adassay/releases/download/v#{version}/adassay_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "942d62e8375c254285099cc5dd899cef1d127842303f524ec7e8f607aef42244"
      url "https://github.com/belaytzev/adassay/releases/download/v#{version}/adassay_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "06247d11d985e69a4672711f89fde6984ce7878511ef267d6de06e2d8f2ed25c"
      url "https://github.com/belaytzev/adassay/releases/download/v#{version}/adassay_#{version}_linux_amd64.tar.gz"
    end
  end

  name "adassay"
  desc "An ad blocker for AI agents"
  homepage "https://adassay.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "adassay"
  binary "adassay-mcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/adassay"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/adassay-mcp"]
    end
  end

  # No zap stanza required
end
