# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitScoper < Formula
  desc "Applies git user.name and user.email to every git repository found in a base directory"
  homepage "https://github.com/belaytzev/git-scoper"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/belaytzev/git-scoper/releases/download/v0.1.0/git-scoper_0.1.0_darwin_amd64.tar.gz"
      sha256 "c92441b864d6f01a8bc04ab5165365514ecd6ad78044b35ca44efe7011d15169"

      define_method(:install) do
        bin.install "git-scoper"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/belaytzev/git-scoper/releases/download/v0.1.0/git-scoper_0.1.0_darwin_arm64.tar.gz"
      sha256 "d36256c07f54b0e7a16ce2ccf3c2d7d740a4438f962c47c7615988ea972b0346"

      define_method(:install) do
        bin.install "git-scoper"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/belaytzev/git-scoper/releases/download/v0.1.0/git-scoper_0.1.0_linux_amd64.tar.gz"
      sha256 "090411bc786f4a197e9f3c4cc65f07d4cc41fbe6ac5dbcc68b1ac421814405d8"
      define_method(:install) do
        bin.install "git-scoper"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/belaytzev/git-scoper/releases/download/v0.1.0/git-scoper_0.1.0_linux_arm64.tar.gz"
      sha256 "a5db350560871b8b488697045314806e27cbd71790a0c8e3c53b21b057b58d81"
      define_method(:install) do
        bin.install "git-scoper"
      end
    end
  end

  test do
    system "#{bin}/git-scoper", "--version"
  end
end
